# Generated by Django 5.2.5 on 2025-10-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_rename_user_userprofile_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='client',
            new_name='user',
        ),
    ]
