# Generated by Django 5.2.5 on 2025-10-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='Campaign')),
                ('published', models.BooleanField(default=True)),
                ('categorys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='Category.category')),
                ('products', models.ManyToManyField(blank=True, default=None, related_name='campaigns', to='Product.product')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='Carousel')),
                ('link', models.URLField()),
                ('published', models.BooleanField(default=True)),
                ('categorys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='Category.category')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
        migrations.CreateModel(
            name='Promo_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='Promo_offer')),
                ('published', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, default=None, related_name='promo_offers', to='Product.product')),
            ],
            options={
                'verbose_name': 'Promo Offer',
                'verbose_name_plural': 'Promo Offers',
            },
        ),
    ]
