# Generated by Django 5.2.5 on 2025-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dblocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='Dblocks')),
                ('link', models.URLField()),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dblock',
                'verbose_name_plural': 'Dblocks',
            },
        ),
    ]
