# Generated by Django 5.2.5 on 2025-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_dblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblocks',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
