# Generated by Django 5.2.5 on 2025-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_dblocks_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('limited_time_text', models.CharField(default='Limited Time Offer', max_length=100)),
                ('end_date', models.DateTimeField()),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
