# Generated by Django 5.2.5 on 2025-10-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon_in_order_landing_page', models.IntegerField(blank=True, default=False, null=True)),
                ('icon_landing_page', models.CharField(blank=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('icon_in_landing_page', models.BooleanField(default=False)),
                ('show_in_dropdown', models.BooleanField(default=False)),
                ('product_overview', models.ImageField(blank=True, null=True, upload_to='Categor Product_overview')),
                ('category_in_landing_page', models.ImageField(blank=True, null=True, upload_to='Category/Category-In-Landing-Page')),
                ('is_popular', models.BooleanField(default=False)),
                ('popular_image', models.ImageField(blank=True, null=True, upload_to='Category/Popular-Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Category/Sub-Category')),
                ('show_in_dropdown', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Category.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='SubPreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Category/Sub-Category/Sub-Pre-Category')),
                ('show_in_dropdown', models.BooleanField(default=True)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='Category.subcategory')),
            ],
            options={
                'verbose_name': 'Sub Pre Category',
                'verbose_name_plural': 'Sub Pre Categories',
            },
        ),
        migrations.CreateModel(
            name='SubPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Category/Sub-Category/Sub-Post-Category/Sub-Post-Category')),
                ('show_in_dropdown', models.BooleanField(default=True)),
                ('SubPreCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubPreCategory', to='Category.subprecategory')),
            ],
            options={
                'verbose_name': 'Sub Post Category',
                'verbose_name_plural': 'Sub Post Categories',
            },
        ),
    ]
