# Generated by Django 5.2.5 on 2025-11-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
